

pvlist = [
    # M1
    {'pvname': 'newport:m21',
     'pvname_alias': 'bl531:m101:pitch_mm',
     'type': 'motor',
     'port': 'ttyUSB300, axis1',
     'unit': 'mm',
     'hight': 1,
     'low': 0,
     'desc':'toroid vertical pitch'
    },

    {'pvname': 'newport:m22',
     'pvname_alias': 'bl531:m101:bend_um',
     'port': 'ttyUSB300, axis2',
     'type': 'motor',
     'unit': 'um',
     'hight': 1,
     'low': 0,
     'desc':'toroid vertical bend'
    },

    {'pvname': 'newport:m23',
     'pvname_alias': 'bl531:m101:slit_st',
     'port': 'ttyUSB300, axis3',
     'type': 'motor',
     'unit': 'st',
     'hight': 1,
     'low': 0,
     'desc':'toroid vertical slit '
    },

    #Mono
    {'pvname': 'IOC:m1',
     'pvname_alias': 'bl531:saxs:mono:angle_deg',
     'port':'192.168.10.25, axis1',
     'type': 'motor',
     'unit': 'deg',
     'hight': 50,
     'low': 0,
     'desc': 'dcm mono vertical angle'
    },
    {'pvname': 'IOC:m2',
     'pvname_alias': 'bl531:saxs:mono:height_mm',
     'port':'192.168.10.25, axis 2',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'dcm mono vertical height'
    },

    #JJ slit before HS
    {'pvname': 'DMC01:A',
     'pvname_alias': 'bl531:saxs:hs_slit:A',
     'port':'192.168.10.21, slit',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit in front of HS'
    },
    {'pvname': 'DMC01:B',
     'pvname_alias': 'bl531:saxs:hs_slit:B',
     'port':'192.168.10.21, slit',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit in front of HS'
    },
    {'pvname': 'DMC01:C',
     'pvname_alias': 'bl531:saxs:hs_slit:C',
     'port':'192.168.10.21, slit',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit in front of HS'
    },
    {'pvname': 'DMC01:D',
     'pvname_alias': 'bl531:saxs:hs_slit:D',
     'port':'192.168.10.21, slit',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit in front of HS'
    },
    {'pvname': 'DMC01:E',
     'pvname_alias': 'bl531:saxs:hs_slit:E',
     'port':'192.168.10.21, slit',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit in front of HS'
    },
    {'pvname': 'DMC01:F',
     'pvname_alias': 'bl531:saxs:hs_slit:F',
     'port':'192.168.10.21, slit',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit in front of HS'
    },
    {'pvname': 'DMC01:G',
     'pvname_alias': 'bl531:saxs:hs_slit:G',
     'port':'192.168.10.21, slit',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit in front of HS'
    },
    {'pvname': 'DMC01:H',
     'pvname_alias': 'bl531:saxs:hs_slit:H',
     'port':'192.168.10.21, slit',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit in front of HS'
    },

    #HS
    {'pvname': 'micronix:m1',
     'pvname_alias': 'bl531:saxs:hs',
     'port':'ttyMMC200',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'HS '
    },

    #JJ slit after HS
    {'pvname': 'DMC02:E',
     'pvname_alias': 'bl531:saxs:sample_slit:E',
     'port':'192.168.10.21, slitE',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit after HS'
    },
    {'pvname': 'DMC02:F',
     'pvname_alias': 'bl531:saxs:sample_slit:F',
     'port':'192.168.10.21, slitF',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit after HS'
    },
    {'pvname': 'DMC02:G',
     'pvname_alias': 'bl531:saxs:sample_slit:G',
     'port':'192.168.10.21, slitG',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit after HS'
    },
    {'pvname': 'DMC02:H',
     'pvname_alias': 'bl531:saxs:sample_slit:H',
     'port':'192.168.10.21, slitH',
     'type': 'motor',
     'unit': 'mm',
     'hight': 50,
     'low': 0,
     'desc': 'JJ slit after HS'
    },
    
    #sample Hexapod
    {'pvname': 'BL531:hxp:c0:m1',
     'pvname_alias': 'bl531:saxs:hxp:x_mm',
     'port':'192.168.10.254',
     'type': 'motor',
     'unit': 'mm',
     'hight': 5,
     'low': 0,
     'desc': 'Hexapod X '
    },
    {'pvname': 'BL531:hxp:c0:m2',
     'pvname_alias': 'bl531:saxs:hxp:y_mm',
     'port':'192.168.10.254',
     'type': 'motor',
     'unit': 'mm',
     'hight': 5,
     'low': 0,
     'desc': 'Hexapod Y '
    },
    {'pvname': 'BL531:hxp:c0:m3',
     'pvname_alias': 'bl531:saxs:hxp:z_mm',
     'port':'192.168.10.254',
     'type': 'motor',
     'unit': 'mm',
     'hight': 5,
     'low': 0,
     'desc': 'Hexapod Z '
    },
    {'pvname': 'BL531:hxp:c0:m4',
     'pvname_alias': 'bl531:saxs:hxp:u_deg',
     'port':'192.168.10.254',
     'type': 'motor',
     'unit': 'deg',
     'hight': 5,
     'low': 0,
     'desc': 'Hexapod U '
    },
    {'pvname': 'BL531:hxp:c0:m5',
     'pvname_alias': 'bl531:saxs:hxp:v_deg',
     'port':'192.168.10.254',
     'type': 'motor',
     'unit': 'deg',
     'hight': 5,
     'low': 0,
     'desc': 'Hexapod V '
    },
    {'pvname': 'BL531:hxp:c0:m1',
     'pvname_alias': 'bl531:saxs:hxp:w_deg',
     'port':'192.168.10.254',
     'type': 'motor',
     'unit': 'deg',
     'hight': 5,
     'low': 0,
     'desc': 'Hexapod W '
    },

    #Beamstop ESP301
    {'pvname': 'bl531:beamstopx_mm',
     'pvname_alias': 'bl531:saxs:beamstop:x_mm',
     'port':'192.168.10.24, x-axis',
     'type': 'motor',
     'unit': 'mm',
     'hight': 5,
     'low': 0,
     'desc': 'Beamstop before Pilatus x-axis'
    },
    {'pvname': 'bl531:beamstopy_mm',
     'pvname_alias': 'bl531:saxs:beamstop:y_mm',
     'port':'192.168.10.24, y-axis',
     'type': 'motor',
     'unit': 'mm',
     'hight': 5,
     'low': 0,
     'desc': 'Beamstop before Pilatus y-axis'
    },

    #open ports (ESP301)
    {'pvname': 'newport:m11',
     'pvname_alias': 'bl531:esp301:x_mm',
     'port':'ttyUSB301, axis1',
     'type': 'motor',
     'unit': 'mm',
     'hight': 5,
     'low': 0,
     'desc': 'Open ports for future devices'
    },
    {'pvname': 'newport:m12',
     'pvname_alias': 'bl531:esp301:y_mm',
     'port':'ttyUSB301, axis2',
     'type': 'motor',
     'unit': 'mm',
     'hight': 5,
     'low': 0,
     'desc': 'Open ports for future devices'
    },
    {'pvname': 'newport:m11',
     'pvname_alias': 'bl531:esp301:z_mm',
     'port':'ttyUSB301, axis3',
     'type': 'motor',
     'unit': 'mm',
     'hight': 5,
     'low': 0,
     'desc': 'Open ports for future devices'
    },

    #Camera
    {'pvname': ' ',
     'pvname_alias': 'bl531:saxs:camera:basler_color',
     'port':'192.168.10.200',
     'type': 'camera',
     'unit': None,
     'hight': 0,
     'low': 0,
     'desc': None
    },
    {'pvname': 'basler5472:image1:',
     'pvname_alias': 'bl531:saxs:camera:basler_mono',
     'port':'192.168.10.204',
     'type': 'camera',
     'unit': None,
     'hight': 0,
     'low': 0,
     'desc': None
    },
    {'pvname': ' ',
     'pvname_alias': 'bl531:saxs:camera:manta',
     'port':'192.168.10.80',
     'type': 'camera',
     'unit': None,
     'hight': 0,
     'low': 0,
     'desc': None
    },

    #Detector
    {'pvname': 'dec1958:image1:',
     'pvname_alias': 'bl531:saxs:pilatus1M',
     'port':'192.168.10.60',
     'type': 'areaDetector',
     'unit': None,
     'hight': 0,
     'low': 0,
     'desc': None
    },
    {'pvname': ' ',
     'pvname_alias': 'bl531:saxs:pilatus300K',
     'port':' ',
     'type': 'areaDetector',
     'unit': None,
     'hight': 0,
     'low': 0,
     'desc': None
    },

    #Sensors
    {'pvname': 'bl531:LTJ4:1',
     'pvname_alias': 'bl531:saxs:labjack',
     'port':' ',
     'type': 'sensor',
     'unit': None,
     'hight': 0,
     'low': 0,
     'desc': None
    },
]